meta:
  site_title: "Seattle Hacks"
  site_subtitle: "For Seattle developers, by Seattle developers"
  site_language: "en"
  absolute_baseurl: http://criticalmasstourist.github.io/seattlehacks/
  baseurl: "/seattlehacks/"
  domain: criticalmasstourist.github.io
  author:
    full_name: Carter Rabasa
    short_name: crabasa
    email: carter@rabasa.com

pygments: true
markdown: rdiscount
permalink: pretty
